#!/usr/bin/env python3
from __future__ import annotations
import json
import re
from pathlib import Path
from datetime import datetime

BASE = Path('/Users/wxo/Desktop/Kronos')
GUARD = BASE / 'guard_outputs'
DAILY = BASE / 'daily_reports'

# Expected trading slots are now derived from active cron + known fixed points.
# Afternoon expected slots are generated by scripts/build_expected_slots_from_active_cron.py
MORNING_SLOTS = ["0930","0940","0950","1000","1010","1020","1030","1040","1050","1100","1110","1120","1130"]
CLOSE_SLOTS = ["1500"]
CRITICAL = {"0930","1450","1500"}


def load_expected(date: str):
    exp = GUARD / f"expected_slots_{date}.json"
    if exp.exists():
        d=json.loads(exp.read_text(encoding='utf-8'))
        return sorted(set([x for x in d.get('expected_timeslots',[]) if x]))
    return []


def parse_report_action_reason(text: str):
    act = None
    reason = None
    full_lock = None
    for ln in text.splitlines():
        if ln.startswith('动作：'):
            act = ln.replace('动作：','',1).strip()
        if ln.startswith('理由：'):
            reason = ln.replace('理由：','',1).strip()
        if ln.startswith('【审计】') and '满仓锁定' in ln:
            m=re.search(r"满仓锁定:\s*(true|false)", ln)
            if m:
                full_lock = (m.group(1)=='true')
    return act, reason, full_lock


def main():
    import argparse
    ap=argparse.ArgumentParser()
    ap.add_argument('date', help='YYYYMMDD')
    args=ap.parse_args()
    d=args.date

    # locate reports for day
    rpt = sorted(GUARD.glob(f'report_{d}_*.txt'))
    check = {p.stem.replace('report_',''): p for p in rpt}

    expected_slots = MORNING_SLOTS + load_expected(d) + CLOSE_SLOTS

    # Defensive: if CLOSE_SLOTS are expected but their report files are not yet
    # present, wait and rescan once (avoids racing with close_snapshot write).
    import time
    missing_close = [s for s in CLOSE_SLOTS if not any(
        k.startswith(f"{d}_{s}00") or k.startswith(f"{d}_{s}0") for k in check
    )]
    if missing_close:
        time.sleep(10)
        rpt = sorted(GUARD.glob(f'report_{d}_*.txt'))
        check = {p.stem.replace('report_',''): p for p in rpt}

    # Optional: join with cron_runs_{date}.json if present
    cron_runs_path = GUARD / f"cron_runs_{d}.json"
    cron_runs = {}
    if cron_runs_path.exists():
        try:
            cj = json.loads(cron_runs_path.read_text(encoding='utf-8'))
            for e in cj.get('entries', []):
                ts = str(e.get('timeslot') or '')
                if not ts:
                    continue
                # Keep the latest run per slot (by runAtMs)
                prev = cron_runs.get(ts)
                if (not prev) or int(e.get('runAtMs') or 0) >= int(prev.get('runAtMs') or 0):
                    cron_runs[ts] = e
        except Exception:
            cron_runs = {}

    def classify_model_error(err_text: str, summary_text: str, last_err_text: str, model_field: str | None):
        blob = "\n".join([err_text or "", summary_text or "", last_err_text or "", model_field or ""]).strip()
        if not blob:
            return None

        # 1) Model not found gpt-5.3-codex
        m = re.search(r"Model not found\s+([\w\-\.]+)", blob, flags=re.IGNORECASE)
        if m:
            return {
                'error_category': 'MODEL_ERROR',
                'error_code': 'MODEL_NOT_FOUND',
                'error_detail': m.group(1),
                'model_used': m.group(1),
            }

        # 2) gpt-5.1 model is not supported / not supported when using Codex with a ChatGPT account
        m = re.search(r"(gpt-[\d\.]+).*not supported", blob, flags=re.IGNORECASE)
        if m:
            return {
                'error_category': 'MODEL_ERROR',
                'error_code': 'MODEL_NOT_SUPPORTED',
                'error_detail': m.group(1),
                'model_used': m.group(1),
            }

        if 'MODEL_ERROR' in blob or 'model' in blob.lower():
            return {
                'error_category': 'MODEL_ERROR',
                'error_code': 'MODEL_UNKNOWN',
                'error_detail': '',
                'model_used': model_field or '',
            }

        return None

    # Optional: model guard daily records
    mg_path = GUARD / f"model_guard_daily_{d}.json"
    mg_by_slot = {}
    if mg_path.exists():
        try:
            mg = json.loads(mg_path.read_text(encoding='utf-8'))
            for e in mg.get('entries', []):
                ts = str(e.get('ts') or '')
                # ts format: YYYY-MM-DD HH:MM:SS
                m = re.search(r"\b(\d{2}):(\d{2})\b", ts)
                if not m:
                    continue
                slot = f"{m.group(1)}{m.group(2)}"
                mg_by_slot[slot] = e
        except Exception:
            mg_by_slot = {}

    rows=[]
    for slot in expected_slots:
        # reports are like report_YYYYMMDD_HHMMSS.txt
        matched = None
        for k,p in check.items():
            if k.startswith(f"{d}_{slot}00") or k.startswith(f"{d}_{slot}0"):
                matched = p
                break

        scheduled = True
        has_report = bool(matched)

        # Pull cron run info (if present)
        run = cron_runs.get(slot)
        run_status = (run.get('status') if run else None)
        run_error = (run.get('error') if run else None)
        run_summary = (run.get('summary') if run else None)
        run_last_error = (run.get('lastError') if run else None)
        model_used = (run.get('model') if run else None)
        provider_used = (run.get('provider') if run else None)
        delivered = (run.get('delivered') if run else None)
        delivery_status = (run.get('deliveryStatus') if run else None)

        status='UNKNOWN'
        error_code=''
        error_category=''
        error_detail=''
        retry_count=0
        report_file=str(matched) if matched else ''
        reason=''

        if has_report:
            txt=matched.read_text(encoding='utf-8',errors='ignore')
            act, rsn, full_lock = parse_report_action_reason(txt)
            status='SUCCESS'
            reason=f"action={act or ''} full_lock={full_lock}"
            if ('行情获取失败（' in txt) or ('行情获取失败' in txt and 'error_code：' in txt):
                status='FAIL'
                m=re.search(r"error_code：([^\n]+)", txt)
                if m:
                    error_code=m.group(1).strip()
        else:
            # no report file. Distinguish between not triggered vs triggered(error)
            if run is None:
                status='SCHEDULED_NOT_TRIGGERED'
                error_code='UNKNOWN_MISSING_SLOT'
                reason='expected by active cron, but no report and no cron run record'
            else:
                # There is a run record but report not generated
                if str(run_status).lower() == 'error':
                    mcls = classify_model_error(str(run_error or ''), str(run_summary or ''), str(run_last_error or ''), str(model_used or ''))
                    if mcls:
                        status='MODEL_ERROR'
                        error_category=mcls['error_category']
                        error_code=mcls['error_code']
                        error_detail=mcls['error_detail']
                        model_used = mcls.get('model_used') or model_used
                    else:
                        status='EXEC_ERROR'
                        error_category='EXEC_ERROR'
                        error_code='RUN_STATUS_ERROR'
                        error_detail=str(run_error or run_summary or '')[:200]
                    reason='cron run status=error; report_generated=false'
                else:
                    status='TRIGGERED_NO_REPORT'
                    error_category='REPORT'
                    error_code='REPORT_GENERATED_FALSE'
                    reason='cron run status!=error but report file not found'

        mg = mg_by_slot.get(slot)
        rows.append({
            'timeslot': slot,
            'scheduled': scheduled,
            'triggered': bool(run) or has_report,
            'status': status,
            'error_category': error_category,
            'error_code': error_code,
            'error_detail': error_detail,
            'model_used': model_used or '',
            'provider_used': provider_used or '',
            'retry_count': retry_count,
            'report_file': report_file,
            'delivered': delivered,
            'deliveryStatus': delivery_status,
            'reason': reason,
            'critical': slot in CRITICAL,

            # P1.1 model guard fields (best-effort join by HH:MM -> timeslot)
            'model_guard_checked': bool(mg),
            'model_guard_pass': (bool(mg.get('allowlist_pass')) if mg else False),
            'original_model': (mg.get('original_model') if mg else ''),
            'final_model': (mg.get('final_model') if mg else ''),
            'fallback_model': (mg.get('fallback_model') if mg else ''),
            'fallback_result': (mg.get('fallback_result') if mg else ''),
        })

    out_json = GUARD / f'slot_coverage_daily_{d}.json'
    out_md = DAILY / f'slot_coverage_summary_{d}.md'
    missing=[r for r in rows if r['status'] not in ('SUCCESS',)]
    critical_missing_slots = [r['timeslot'] for r in missing if r.get('critical')]
    is_full_trading_day_sample = (len(missing) == 0 and len(critical_missing_slots) == 0)
    sample_status = 'full_day_complete' if is_full_trading_day_sample else 'partial_day_interrupted_by_request_aborted_and_scheduler_backoff'
    performance_use_allowed = bool(is_full_trading_day_sample)
    error_code_daily = 'abnormal' if len(missing) > 0 else 'normal'
    primary_error_pattern = 'UNKNOWN_MISSING_SLOT' if len(missing) > 0 else 'NONE'
    root_cause_class = (
        'scheduler_backoff_after_request_aborted'
        if '0930' in critical_missing_slots
        else ('none' if len(missing) == 0 else 'unknown_missing_slot')
    )

    quality_flags = {
        'error_code_daily': error_code_daily,
        'primary_error_pattern': primary_error_pattern,
        'root_cause_class': root_cause_class,
        'sample_status': sample_status,
        'is_full_trading_day_sample': is_full_trading_day_sample,
        'performance_use_allowed': performance_use_allowed,
        'not_for_strategy_eval': not performance_use_allowed,
        'not_for_parameter_switch': not performance_use_allowed,
        'not_for_v1_2_shadow_enable': not performance_use_allowed,
        'critical_missing_slots': critical_missing_slots,
        'missing_slot_count': len(missing),
    }

    out_json.write_text(json.dumps({'date': d, 'generated_at': datetime.now().strftime('%Y-%m-%d %H:%M:%S'), **quality_flags, 'slots': rows}, ensure_ascii=False, indent=2), encoding='utf-8')

    md=[
        f"# slot_coverage_summary {d}",
        f"- generated_at: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        f"- total_slots: {len(rows)}",
        f"- missing_slots: {len(missing)}",
        f"- critical_missing: {', '.join([r['timeslot'] for r in missing if r['critical']]) or 'none'}",
        "",
        "## Sample Quality",
        f"- sample_status: {sample_status}",
        f"- is_full_trading_day_sample: {str(is_full_trading_day_sample).lower()}",
        f"- performance_use_allowed: {str(performance_use_allowed).lower()}",
        f"- not_for_strategy_eval: {str((not performance_use_allowed)).lower()}",
        f"- not_for_parameter_switch: {str((not performance_use_allowed)).lower()}",
        f"- not_for_v1_2_shadow_enable: {str((not performance_use_allowed)).lower()}",
        f"- critical_missing_slots: {', '.join(critical_missing_slots) or 'none'}",
        f"- missing_slot_count: {len(missing)}",
        "",
        "## Key slots",
    ]

    # Mandatory explicit display for 14:20 / 14:40 / 14:50 when present in expected slots
    for k in ['1420','1440','1450']:
        r = next((x for x in rows if x['timeslot']==k), None)
        if not r:
            continue
        md.append(f"- {k}: {r['status']} / {r.get('error_code','')} / model_used={r.get('model_used','')}")

    md += ["", "## Missing detail"]
    for r in missing:
        md.append(
            f"- {r['timeslot']}: {r['status']} {r.get('error_category','')} {r.get('error_code','')} "
            f"model={r.get('model_used','')} ({r.get('reason','')})"
        )

    out_md.write_text('\n'.join(md)+'\n', encoding='utf-8')
    print(out_json)
    print(out_md)

if __name__=='__main__':
    main()
